const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_POSTS: "GET_POSTS",
  GET_POSTS_HOME_PAGE_LIMIT: "GET_POSTS_HOME_PAGE_LIMIT",
  GET_AREAS: "GET_AREAS",
  GET_PRICES: "GET_PRICES",
};

export default actionTypes;
